import { parseFrontmatter, renderFrontmatter } from '../util/frontmatter.ts';

/**
 * Opt-in generated adapter: Claude Code subagent (.claude/agents/<n>.md) → OpenCode agent
 * (.opencode/agents/<n>.md). Only `description`, `mode: subagent` and the body map cleanly;
 * every other Claude field is dropped and listed in the header so nobody mistakes the
 * projection for a faithful copy. Reserved OpenCode names are refused.
 */
const OPENCODE_RESERVED = new Set(['plan', 'build', 'general', 'explore', 'compaction', 'summary', 'title']);
const CLAUDE_FIELDS_DROPPED = ['tools', 'disallowedTools', 'model', 'permissionMode', 'skills', 'memory', 'isolation', 'maxTurns', 'hooks', 'background', 'mcpServers', 'color'];

export function generateOpenCodeAgent(sourcePath: string, sourceText: string, id: string): { name: string; content: string; dropped: string[] } | { error: string } {
  const fm = parseFrontmatter(sourceText);
  if (!fm.present || fm.error) return { error: `${sourcePath}: source has no valid frontmatter (${fm.error ?? 'missing'})` };
  const name = typeof fm.data['name'] === 'string' ? fm.data['name'] : sourcePath.split('/').pop()!.replace(/\.md$/, '');
  if (OPENCODE_RESERVED.has(name)) return { error: `${sourcePath}: agent name '${name}' would override a built-in OpenCode agent; rename the source or skip the adapter` };
  const description = typeof fm.data['description'] === 'string' ? fm.data['description'] : '';
  if (!description) return { error: `${sourcePath}: description is required` };
  const dropped = CLAUDE_FIELDS_DROPPED.filter((k) => fm.data[k] !== undefined);
  const header = [
    `<!-- agentconcord:generated id=${id} source=${sourcePath} -->`,
    `<!-- Generated by AgentConcord from ${sourcePath}. Edit the source, then run \`agentconcord apply\`.`,
    `     Dropped Claude-only fields: ${dropped.length ? dropped.join(', ') : 'none'}. OpenCode permissions inherit defaults. -->`,
  ].join('\n');
  const body = `${header}\n\n${fm.body.trim()}\n`;
  const content = renderFrontmatter({ description, mode: 'subagent' }, `\n${body}`);
  return { name, content, dropped };
}
